### PR TITLE
basic auth support

### PR DESCRIPTION
**Pull request by lockwobr**
added support of for http://username:password@domain.com, by default this does not work with webclient, however the scollector works this way.

I have tested this patch and it works in my env. Using basic auth with ngnix reverse proxy behind tls. ngnix was throwing this error in the error.log:
2015/07/25 03:30:17 [error] 61778#0: *143774 no user/password was provided for basic authentication

### CODE REVIEW

**Comment by bretcope** [comment]
Thanks for contributing. I'll gladly take this feature, but a few things need to change before I can accept this PR.

* There is a binary "Code" file committed to the root of the repository. I have no idea what this is, but it looks like it was put there by accident and should be removed.
* I know it's a personal preference, but `false == ` feels awkward and doesn't match the coding style used anywhere else. Let's just stick with `if (!string.IsNullOrEmpty(userInfo))`
* Instead of `string.Format()`, we use the C#6 `$"{obj}"` syntax now. Although, in this case, straight concatenation would actually be my preference `"Basic " + base64`.
* I don't love the `Build.md` file. It's completely unrelated to this PR. I also feel like if there really _needs_ to be a notice about C#6, it should probably be a quick note on the README. With VS 2015 officially released now, I consider C#6 the standard to be expected from projects rather than an exceptional case. But I'm open to discussing that further, just not as part of a PR on http auth.

If you'd like to make those changes, and squash into one commit, I'll happily merge it.

**Comment by bretcope** [comment]
* There is also a typo (superfluous "of") in the comment `// support of for...`

**Comment by lockwobr** [comment]
I have those changes made, should I open a new pull request?

I think you should include something about VS2015, but that being said, it a month or so it will not be as important. I just took me so time figure out that is what I needed to do to build the project.

**Comment by bretcope** [comment]
Looks good. Could you squash these commits into one for me? It's not always a strict requirement for a pull request, but it'd be nice not to have seven commits for such a small change. Also, squashing it will keep that binary Code file out of revision history.

Thanks.

---

If you're unfamiliar with how to to squash:

Use `git rebase -i 5c5cda2a85b3eeeb1b542e351be9407fcb139306` (that's the last commit hash on master before your changes).

Edit the first commit message in the list to be representative of the changes, such as "Add support for http basic auth."

For all commits after the first one, switch "pick" to "fixup" and save.

Then you'll need to do a force push `git push --force` to update history, which should get picked up by this PR.

**Comment by lockwobr** [comment]
well i did it but not sure it worked right...

**Comment by bretcope** [comment]
Sorry, I left out that you need to use "reword" instead of "pick" for the first one in order to edit the commit message. Not sure if that's what you got caught up on or not.

It's probably easier for me to just do the rebase than to troubleshoot, so that's what I've done. It's merged now, even though this PR won't display as such. Should be available as `2.0.2` on nuget within a few minutes.

I didn't realize how long it had been since issuing a stable release, so this was a good reminder to do so.

**Pull request closed without merging**
